conda create -n OVG-NAV python=3.7
conda activate OVG-NAV
pip install transformers
conda install pytorch==1.9.1 torchvision==0.10.1 torchaudio==0.9.1 cudatoolkit=10.2 -c pytorch -y
pip install ftfy regex tqdm
pip install git+https://github.com/openai/CLIP.git
python -m pip install detectron2 -f https://dl.fbaipublicfiles.com/detectron2/wheels/cu102/torch1.9/index.html
pip install gitpython
conda install habitat-sim=0.2.2 withbullet headless -c conda-forge -c aihabitat
pip install opencv-python
pip install scikit-learn
pip install quaternion
pip install scikit-image
git clone --branch stable https://github.com/facebookresearch/habitat-lab.git
cd habitat-lab/
git checkout v0.2.2
pip install -e .
pip install -r requirements.txt
python setup.py develop --all
pip install scikit-fmm
pip install seaborn
